const saved=JSON.parse(localStorage.getItem('lystra-state')||'null');
const state=saved||{month:'October 2026',budget:5000,filter:'all',items:[
{name:'Everyday sneakers',price:2499,category:'Fashion',priority:'Essential',status:'wishlist',why:'My current shoes hurt after walking around campus.',url:''},
{name:'Silver hoops',price:799,category:'Fashion',priority:'Want',status:'wishlist',why:'Would go with basically everything.',url:''},
{name:'Hair serum',price:649,category:'Beauty',priority:'Essential',status:'wishlist',why:'Running low on my current one.',url:''},
{name:'Tote bag',price:1299,category:'Lifestyle',priority:'Maybe',status:'wishlist',why:'Cute, but I already have one.',url:''}
]};
function persist(){localStorage.setItem('lystra-state',JSON.stringify(state))}
const $=id=>document.getElementById(id); const money=n=>'₹'+Number(n).toLocaleString('en-IN');
function start(){ $('landing').style.display='none'; $('dashboard').style.display='block'; render(); window.scrollTo({top:0,behavior:'smooth'}); }
function render(){ $('monthTitle').textContent=state.month; $('monthInput').value=state.month; $('budgetVal').textContent=money(state.budget); const planned=state.items.filter(x=>x.status!=='bought').reduce((s,x)=>s+x.price,0); const spent=state.items.filter(x=>x.status==='bought').reduce((s,x)=>s+x.price,0); const left=state.budget-planned-spent; $('plannedVal').textContent=money(planned); $('leftVal').textContent=money(left); $('budgetBar').style.width=Math.min(100,Math.max(0,(planned+spent)/state.budget*100))+'%';
const filtered=state.items.filter(x=>state.filter==='all'?true:state.filter==='bought'?x.status==='bought':x.priority===state.filter); const grid=$('grid'); grid.innerHTML=''; if(!filtered.length){grid.innerHTML='<div class="empty">Nothing here yet.<br><span style="font-size:14px">Maybe that is the point.</span></div>'} filtered.forEach((x,i)=>{const real=state.items.indexOf(x); const c=document.createElement('article'); c.className='card'; c.innerHTML=`<div><div class="card-top"><span class="tag">${x.category} · ${x.priority}</span><span style="font-size:16px">${x.status==='bought'?'✓':''}</span></div><h3>${esc(x.name)}</h3><div class="price">${money(x.price)}</div>${x.why?`<div class="why">“${esc(x.why)}”</div>`:''}</div><div class="card-bottom">${x.url?`<a class="link" target="_blank" rel="noopener" href="${esc(x.url)}">View product ↗</a>`:'<span class="link" style="opacity:.35">no link yet</span>'}<button class="bought" onclick="toggleBought(${real})">${x.status==='bought'?'Mark wishlist':'Mark bought ✓'}</button></div>`;grid.appendChild(c)}); $('reflectionText').textContent=state.items.length?`You have ${state.items.filter(x=>x.status==='bought').length} bought and ${state.items.filter(x=>x.status!=='bought').length} still on the list. You planned ${money(planned)} before buying — now you get to decide what deserves a place in your month.`:'Your list is empty. Start with one thing you are genuinely considering.'; }
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function openModal(){$('overlay').style.display='flex';$('name').focus()} function closeModal(){$('overlay').style.display='none'} function addItem(e){e.preventDefault();state.items.unshift({name:$('name').value,price:+$('price').value,url:$('url').value,category:$('category').value,priority:$('priority').value,status:'wishlist',why:$('why').value});e.target.reset();persist();closeModal();render()}
function toggleBought(i){state.items[i].status=state.items[i].status==='bought'?'wishlist':'bought';persist();render()}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.f;render()}));
function setMonth(v){state.month=v||state.month;persist();render()} function shiftMonth(delta){const d=new Date(state.month+' 1');d.setMonth(d.getMonth()+delta);state.month=d.toLocaleString('en-US',{month:'long',year:'numeric'});persist();render()}
$('overlay').addEventListener('click',e=>{if(e.target.id==='overlay')closeModal()});
